# Generated by Django 5.2 on 2025-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
