# Generated by Django 5.2 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default_image.jpg', upload_to='books'),
        ),
    ]
