# Generated by Django 5.2 on 2025-12-22 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_booklike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booklike',
            unique_together={('book', 'user')},
        ),
    ]
